spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:storage}
      grid-fs-database: ${MONGO_GRIDFS_DATABASE:storage}
      username: ${MONGO_USERNAME:storage}
      password: ${MONGO_PASSWORD:storage}
